// This file is generated by scripts/sync-github-projects.mjs.
// Do not edit it manually; edit selected-repositories.ts or project-curation.ts instead.

import type { SelectedRepositoryName } from "@/data/selected-repositories";

export type GitHubProjectMetadata = {
  repositoryName: SelectedRepositoryName;
  owner: "dorakingx";
  githubUrl: string;
  description: string | null;
  homepageUrl: string | null;
  primaryLanguage: string | null;
  topics: readonly string[];
  starCount: number;
  updatedAt: string;
};

export const githubProjectMetadata = [
  {
    "repositoryName": "aiterval",
    "owner": "dorakingx",
    "githubUrl": "https://github.com/dorakingx/aiterval",
    "description": null,
    "homepageUrl": "https://aiterval-build-week.vercel.app/",
    "primaryLanguage": "TypeScript",
    "topics": [],
    "starCount": 0,
    "updatedAt": "2026-07-19T09:18:51Z"
  },
  {
    "repositoryName": "novelpilot",
    "owner": "dorakingx",
    "githubUrl": "https://github.com/dorakingx/novelpilot",
    "description": null,
    "homepageUrl": "https://novelpilot.vercel.app/",
    "primaryLanguage": "TypeScript",
    "topics": [],
    "starCount": 4,
    "updatedAt": "2026-06-26T15:31:46Z"
  },
  {
    "repositoryName": "qisquiz",
    "owner": "dorakingx",
    "githubUrl": "https://github.com/dorakingx/qisquiz",
    "description": null,
    "homepageUrl": "https://qisquiz.vercel.app/",
    "primaryLanguage": "TypeScript",
    "topics": [],
    "starCount": 0,
    "updatedAt": "2026-06-03T02:58:23Z"
  },
  {
    "repositoryName": "musiq",
    "owner": "dorakingx",
    "githubUrl": "https://github.com/dorakingx/musiq",
    "description": null,
    "homepageUrl": "https://musiquantum.vercel.app/",
    "primaryLanguage": "OpenQASM",
    "topics": [],
    "starCount": 1,
    "updatedAt": "2026-06-26T14:47:38Z"
  },
  {
    "repositoryName": "AlphaQuoridor",
    "owner": "dorakingx",
    "githubUrl": "https://github.com/dorakingx/AlphaQuoridor",
    "description": null,
    "homepageUrl": null,
    "primaryLanguage": "Python",
    "topics": [],
    "starCount": 1,
    "updatedAt": "2025-08-16T11:18:18Z"
  },
  {
    "repositoryName": "QSimCity",
    "owner": "dorakingx",
    "githubUrl": "https://github.com/dorakingx/QSimCity",
    "description": "An explorable 3D quantum city driven by real computation traces. Unofficial, independent educational and research visualization project.",
    "homepageUrl": "https://qsimcity.vercel.app/",
    "primaryLanguage": "TypeScript",
    "topics": [],
    "starCount": 0,
    "updatedAt": "2026-07-31T09:44:58Z"
  }
] as const satisfies readonly GitHubProjectMetadata[];
